---
- name: Configure nginx backends
  copy:
    src: roles/configure-nginx-backends/files/default
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Configure nginx backends2
  template:
    src: roles/configure-nginx-backends/files/index.php.j2
    dest: /var/www/html/index.php
    owner: root
    group: root
    mode: '0644'
