---
- name: install packages ... pcm
  become: true
  hosts: web
  roles:
    - role: install-pacemaker
    - role: iscsi-client

- name: install packages ... iscsi
  become: true
  hosts: iscsi
  roles:
    - role: iscsi-target

- name: create target
  become: true
  hosts: iscsi
  roles:
    - role: create-target

- name: create initiator
  become: true
  hosts: web
  roles:
    - role: create-initiator

- name: config GFS2
  become: true
  hosts: web00
  roles:
    - role: config-gfs2


###############################
- name: install keepalive
  become: true
  hosts: fe
  roles:
    - role: install-keepalive

- name: install nginx
  become: true
  hosts: web
  roles:
    - role: install-nginx

- name: install php
  become: true
  hosts: web
  roles:
    - role: install-php


- name: install mysql
  become: true
  hosts: db
  roles:
    - role: install-mysql

- name: configure keepalive
  become: true
  hosts: fe
  roles:
    - role: configure-keepalived

- name: configure-nginx-fronts
  become: true
  hosts: fe
  roles:
    - role: configure-nginx-fronts

- name: configure-nginx-backends
  become: true
  hosts: web
  roles:
    - role: configure-nginx-backends

- name: configure-mysql
  become: true
  hosts: db
  roles:
    - role: configure-mysql
