---
- name: Install epel-release
  yum:
    update_cache: yes
    state: latest
    name:
      - epel-release

- name: Install php-fpm | php-mysql
  yum:
    update_cache: yes
    state: present
    name:
      - php-fpm
      - php
      - php-mysql
      - nginx
      - libselinux-python
      - libselinux-python3

- name: Disable Selinux
  selinux: policy=targeted state=permissive
