pacemaker_hacluster_user: 'hacluster'
pacemaker_hacluster_sha: '$6$65ZVK3CdSgjLeHOF$vl3r.cjQukU..qQnU5BhIsDFwrCorxUvMY1A83dX8KriWjDqFBevxdmpaS0CjFUYqbesUvQ51SornyHmjppcA/'
pacemaker_hacluster_password: 'haPASS1804'
pacemaker_hacluster_name: 'otusha'
nodes: 'ef3gqtshvgr1srfi414r ef3ickkravffdrj9jsl1 ef3juspvgum0tt0enbk3'
