pacemaker_hacluster_user: 'hacluster'
pacemaker_hacluster_sha: '$6$65ZVK3CdSgjLeHOF$vl3r.cjQukU..qQnU5BhIsDFwrCorxUvMY1A83dX8KriWjDqFBevxdmpaS0CjFUYqbesUvQ51SornyHmjppcA/'
pacemaker_hacluster_password: 'haPASS1804'
pacemaker_hacluster_name: 'otusha'
nodes: 'ef3gm1q3fbpjv5d1r72u ef3ef90c1bf1k0p1jjbi ef39in4vjk0f5c3be24t'
